Update squash.rb
talum/bugs pull request #87
Opened 2023-11-03 13:49 UTC by talum

2023-11-03 13:56 UTC, tracylum approved these changes

2023-12-05 14:41 UTC, talum commented on squash.rb
>  squash.rb
test

2023-12-05 14:41 UTC, talum commented on squash.rb
>  squash.rb
another test

2024-01-25 20:55 UTC, talum commented on squash.rb
> +gourds!
```suggestion
bleh?
```

2024-01-25 22:05 UTC, talum commented on squash.rb
> +gourds!
?

2024-01-25 22:06 UTC, talum commented
?

2024-01-25 22:10 UTC, talum commented on squash.rb
> +gourds!
replying to existing thread

2024-01-25 22:10 UTC, talum commented on squash.rb
>  squash.rb
making a new comment on R1

2024-01-29 19:08 UTC, talum commented
testing

2024-01-29 19:08 UTC, talum commented on squash.rb
>  squash.rb
no suggestion application options here

2024-01-29 19:09 UTC, talum commented on squash.rb
>  squash.rb
```suggestion
hi
```

2024-02-01 15:06 UTC, talum commented on squash.rb
>  squash.rb
```suggestion
squash.rb
```

2024-02-01 15:06 UTC, talum commented on squash.rb
>  squash.rb
```suggestion
squash.rb change me
```

2024-03-19 17:52 UTC, closed without merging

2024-08-26 19:02 UTC, tracylum requested changes
sdf