Update bloop
talum/bugs pull request #88
Opened 2023-12-05 16:14 UTC by talum

2023-12-05 16:15 UTC, talum commented on bloop
> +
from the other side

2023-12-13 14:32 UTC, talum commented on bloop
> +
sdfsf

2023-12-15 20:05 UTC, talum commented on bloop
> +blooping sdfsdf
```suggestion
no bloop
```

2023-12-19 15:56 UTC, talum commented on bloop
> +blooping sdfsdf
another comment

2023-12-19 15:57 UTC, talum commented on bloop
new file level comment and thread

2023-12-19 15:57 UTC, talum commented on bloop
reply

2023-12-19 15:57 UTC, talum commented on bloop
> +
Another comment

2023-12-19 15:57 UTC, talum commented on bloop
> +
another thread

2023-12-19 15:57 UTC, talum reviewed
le boeuf

2023-12-19 15:57 UTC, talum commented on bloop
pending comment

2023-12-19 15:58 UTC, talum commented on bloop
Another comment

2023-12-19 15:58 UTC, talum commented on bloop
reply

2023-12-19 15:58 UTC, talum commented on bloop
> -blooping from @tracylum
add comment to single file view

2023-12-19 15:58 UTC, talum commented on bloop
> +
range comment

2023-12-19 17:07 UTC, talum commented on bloop
hi

2024-01-18 15:53 UTC, talum commented on bloop
> +
L1 to R3

2024-01-18 15:53 UTC, talum commented on bloop
> +no bloop
sdfsdf

2024-01-18 16:00 UTC, talum commented on bloop
> +
multiline

2024-01-18 16:02 UTC, talum commented on bloop
> +
L3 to R4

2024-01-18 16:02 UTC, talum commented on bloop
> +no bloop
L1 to R2

2024-01-18 16:03 UTC, talum commented on bloop
> +
L3 to R4

2024-01-18 16:06 UTC, talum commented on bloop
> +
L3 to R4

2024-01-18 16:06 UTC, talum commented on bloop
> +
sdfsdf

2024-01-18 16:06 UTC, talum commented on bloop
> +
from action bar plus icon

2024-01-18 16:07 UTC, talum commented on bloop
> +
first line

2024-01-18 16:08 UTC, talum commented on bloop
> +
L3 to R4 first line

2024-01-18 16:08 UTC, talum commented on bloop
> +
L3 to R4 last line plus icon

2024-01-18 19:26 UTC, talum commented on bloop
> +l;aksjd;lfkajsd;f
L3 to R5

2024-01-18 19:26 UTC, talum commented on bloop
> +no bloop
L3 to R2?

2024-01-18 19:26 UTC, talum commented on bloop
> +l;aksjd;lfkajsd;f
test?

2024-01-18 19:27 UTC, talum commented on bloop
> -blooping from @tracylum
test

2024-01-18 19:27 UTC, talum commented on bloop
> +no bloop
test

2024-01-18 19:27 UTC, talum commented on bloop
> +l;aksjd;lfkajsd;f
sdfsdf

2024-01-18 19:27 UTC, talum commented on bloop
> -blooping from @tracylum
test

2024-01-18 19:27 UTC, talum commented on bloop
> +
testing

2024-01-19 13:54 UTC, talum commented on bloop
> -bloop
test

2024-01-19 13:54 UTC, talum commented on bloop
> +no bloop
range

2024-01-19 13:55 UTC, talum commented on bloop
> +
```suggestion
no bloop
```

2024-01-19 13:55 UTC, talum commented on bloop
file level

2024-01-19 13:55 UTC, talum commented on bloop
> -bloop
from single file view

2024-01-19 13:55 UTC, talum commented on bloop
single file

2024-01-19 13:55 UTC, talum commented on bloop
new comment single file

2024-01-19 13:55 UTC, talum commented on bloop
> +
```suggestion
no bloop
```

action bar

2024-01-24 17:19 UTC, talum commented on bloop
my pending comment from files

2024-01-24 17:23 UTC, talum commented on bloop
pending

2024-01-24 17:23 UTC, talum commented on bloop
another pending comment from files

2024-02-07 15:02 UTC, talum commented on bloop
file level comment on bloop from files

2024-02-08 14:07 UTC, talum commented on bloop
> +
```suggestion
```

2024-02-28 21:53 UTC, talum commented on bloop
> +l;aksjd;lfkajsd;f
```suggestion
change
```

2024-04-11 13:19 UTC, tracylum requested changes
stahp

2024-07-23 15:07 UTC, merged